print("hello world")
print("second")
print("third")
print("fourth")
print("fifth")
print("sixth")
print("seventh")
print("eighth")
print("ninth")
print("tenth")
print("eleventh")
print("twelfth")
print("thirteenth")
print("fourteenth")